name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2

      - name: Build&Test
        run: make release TAG=${GITHUB_SHA:0:12}

      - name: Deploy
        run: make deploy
